const path = require('node:path');
const fs = require('node:fs');

const dev = process.env.NODE_ENV !== 'production';

/**
 * StyleX compilation runs through Babel alongside `next/babel`. The matching CSS
 * is generated by `@stylexjs/postcss-plugin`, which reuses these same plugin
 * options (see `postcss.config.mjs`).
 *
 * Must be `babel.config.js` (not `.cjs`/`.mjs`): Next's Babel loader only accepts
 * `.js`/`.json`/`.babelrc`, so `apps/web` is a CommonJS package (no
 * `"type": "module"`).
 *
 * `rootDir`: Turbopack evaluates this config in a sandbox where `__dirname` is
 * virtualized to a `/ROOT/`-prefixed path (e.g. `/ROOT/apps/web`). StyleX
 * reconstructs real paths for those aliases via `path.join(rootDir, …)`, so
 * `rootDir` must be the *real* workspace root. `process.cwd()` stays real under
 * Turbopack, so we walk up from it to the pnpm workspace root.
 */
function findRepoRoot(start) {
  let dir = start;
  for (let i = 0; i < 12; i += 1) {
    if (fs.existsSync(path.join(dir, 'pnpm-workspace.yaml'))) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return start;
}

const rootDir = findRepoRoot(process.cwd());

module.exports = {
  presets: ['next/babel'],
  plugins: [
    [
      '@stylexjs/babel-plugin',
      {
        dev,
        runtimeInjection: false,
        treeshakeCompensation: true,
        unstable_moduleResolution: { type: 'commonJS', rootDir },
        // This repo maps `@/` to `apps/web/src` (see tsconfig + AGENTS.md).
        aliases: {
          '@/*': [path.join(__dirname, 'src', '*')],
        },
      },
    ],
  ],
};
