import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/**
 * `games` — one row per game; the single-writer row.
 *
 * Board, deck, played pile, and completed sequences live in jsonb: the game is
 * always loaded/saved whole by one writer in a transaction, so normalizing the
 * 100 board cells buys nothing and costs joins. `version` gives atomic
 * whole-game updates (optimistic concurrency).
 *
 * `created_by` / `rematch_of` reference Better Auth's `user.id` and this table
 * respectively at the application layer. The `user` table is owned and
 * generated by Better Auth (p03-t04); `created_by` is therefore stored as the
 * matching text id without a cross-migration DB-level FK constraint here.
 */

/** jsonb shape: one board cell. `null` chip = empty. */
export interface BoardCell {
  chip?: number; // team id (1-3)
  lockedBy?: number; // sequence id that locked this cell
}

/** jsonb shape: a single card (kept loose; game-logic owns the canonical type). */
export interface CardJson {
  rank: string;
  suit: string;
}

/** jsonb shape: a completed sequence record. */
export interface SequenceJson {
  team: number;
  cells: number[]; // board cell indices
  order: number; // completion order
}

/** jsonb shape: a pending >5-run lock selection awaiting the placer's choice. */
export interface PendingChoiceJson {
  seat: number;
  runLength: number;
  cells: number[];
}

export const gameStatuses = [
  'lobby',
  'active',
  'frozen',
  'saved',
  'finished',
] as const;
export type GameStatus = (typeof gameStatuses)[number];

export const gameModes = ['tap', 'drag'] as const;
export type GameMode = (typeof gameModes)[number];

export const endReasons = ['win', 'concede', 'expired'] as const;
export type EndReason = (typeof endReasons)[number];

export const games = pgTable(
  'games',
  {
    // Identity
    id: uuid('id').primaryKey().defaultRandom(),
    inviteCode: text('invite_code').notNull(),
    createdBy: text('created_by').notNull(),
    rematchOf: uuid('rematch_of'),
    local: boolean('local').notNull().default(false),

    // Settings (immutable after start)
    playerCount: smallint('player_count').notNull(),
    mode: text('mode').$type<GameMode>().notNull(),
    timerSeconds: integer('timer_seconds'),

    // Live state
    status: text('status').$type<GameStatus>().notNull().default('lobby'),
    version: integer('version').notNull().default(0),
    currentSeat: smallint('current_seat'),
    round: integer('round').notNull().default(0),
    turnDeadlineAt: timestamp('turn_deadline_at', { withTimezone: true }),
    turnRemainingMs: integer('turn_remaining_ms'),
    pendingChoice: jsonb('pending_choice').$type<PendingChoiceJson>(),

    // Game data (jsonb)
    board: jsonb('board').$type<BoardCell[]>(),
    deck: jsonb('deck').$type<CardJson[]>(),
    played: jsonb('played').$type<CardJson[]>(),
    sequences: jsonb('sequences').$type<SequenceJson[]>(),

    // Outcome
    winnerTeam: smallint('winner_team'),
    endReason: text('end_reason').$type<EndReason>(),
    finishedAt: timestamp('finished_at', { withTimezone: true }),

    // Lifecycle
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex('games_invite_code_idx').on(table.inviteCode),
    index('games_status_finished_at_idx').on(table.status, table.finishedAt),
  ],
);

export type GameRow = typeof games.$inferSelect;
export type NewGameRow = typeof games.$inferInsert;
