/**
 * Schema barrel — re-exports every table so the Drizzle client and
 * `drizzle-kit` see one canonical schema object.
 *
 * `auth.ts` holds the Better Auth tables (`user`, `session`, `account`,
 * `verification`), generated by the Better Auth CLI.
 */
export * from './auth.ts';
export * from './games.ts';
export * from './game-players.ts';
export * from './game-events.ts';
